"""Turn a scored lead into a hunt-template draft.

A feed entry is a lead, not a behaviour. It gives a headline, a few hundred words of
summary, some CVEs and an actor name; it does not give the parent-child relationship or
the command line that a hunt is built on. So this writes a **draft**, never a template:
everything the feed actually supports is filled in, and the three things it cannot
support -- the hypothesis, the MITRE block and the query -- are left as TODO for whoever
reads the article.

Drafts are named `ETI-<yyyymmdd>-<nnn>-<slug>.yaml` and filed under the run's date, so a
draft always traces back to the day that produced it:

    ETI/templates/2026-10-03/ETI-20261003-001-fortinet-kev-exploited.yaml

A lead is drafted once, in two senses. `state/drafted.csv` maps the lead URL to the draft
that covers it, so a URL seen again is not drafted again. And within a run, the retellings
of one story collapse into the highest-scoring of them: ten outlets rewriting one vendor
post is one piece of work, not ten. Two rows are the same story when they corroborate each
other -- that relation is symmetric and non-transitive by construction in corroborate.py,
so it cannot chain a Patch Tuesday roundup into everything it touches.

What it does not do is collapse a retelling published *tomorrow* into today's draft: that
arrives as a new URL on a later run, and a fresh article on a known story is often worth
the second look.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

# Words that carry no meaning in a filename and only spend its length budget.
_STOP = {
    "a", "an", "the", "and", "or", "of", "for", "to", "in", "on", "with", "from",
    "new", "news", "says", "it", "is", "are", "as", "at", "by", "that", "this",
}
_SLUG_WORDS = 6
_SLUG_CHARS = 48

DRAFT_HEADER = "ETI"


def slugify(title: str, *, words: int = _SLUG_WORDS, chars: int = _SLUG_CHARS) -> str:
    """A short, readable, filename-safe handle for a lead."""
    bare = re.sub(r"[^a-z0-9]+", " ", (title or "").lower()).split()
    kept = [w for w in bare if w not in _STOP] or bare
    slug = "-".join(kept[:words])[:chars].strip("-")
    return slug or "untitled"


def draft_name(day: str, seq: int, slug: str) -> str:
    """ETI-20261003-001-fortinet-kev-exploited"""
    return "%s-%s-%03d-%s" % (DRAFT_HEADER, day.replace("-", ""), seq, slug)


def _q(value) -> str:
    """Quote a scalar for YAML. Feed titles are other people's text."""
    text = "" if value is None else str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _seq(items: list[str]) -> str:
    """A YAML flow sequence, or [] when empty."""
    return "[%s]" % ", ".join(_q(i) for i in items) if items else "[]"


def _split(cell: str) -> list[str]:
    """The CSV packs multi-values into one semicolon-joined cell."""
    return [p for p in (cell or "").split(";") if p]


def _wrap(text: str, indent: int, width: int = 92) -> str:
    pad = " " * indent
    lines, cur = [], ""
    for word in (text or "").split():
        if cur and len(pad) + len(cur) + 1 + len(word) > width:
            lines.append(pad + cur)
            cur = word
        else:
            cur = (cur + " " + word).strip()
    if cur:
        lines.append(pad + cur)
    return "\n".join(lines) or (pad + "TODO")


def render(row: dict, name: str, *, stamp: str) -> str:
    """The draft for one lead."""
    cves = _split(row.get("cves", ""))
    actors = _split(row.get("actors", ""))
    tags = _split(row.get("tags", ""))
    behaviours = _split(row.get("behaviours", ""))
    mentioned = _split(row.get("attack_ids_mentioned", ""))
    others = _split(row.get("corroborated_by", ""))

    out: list[str] = []
    w = out.append
    w("# ETI draft -- generated by ETI/eti/draft.py from a threat-intel feed item.")
    w("# This is NOT a detection template. It carries what the feed supports and leaves")
    w("# the hypothesis, the MITRE block and the query open. See ETI/templates/README.md.")
    w("type: detection-draft")
    w("status: draft")
    w("id: %s" % name.lower())
    w("version: 0.1.0")
    w("generated: %s" % stamp)
    w("")
    w("# ---------------------------------------------------------------------------")
    w("# The lead, as the feed reported it. Facts about the publication, not the threat.")
    w("# ---------------------------------------------------------------------------")
    w("lead:")
    w("  title: %s" % _q(row.get("title")))
    w("  url: %s" % _q(row.get("url")))
    w("  source: %s" % _q(row.get("source")))
    w("  source_id: %s" % _q(row.get("source_id")))
    w("  published_utc: %s" % _q(row.get("published_utc")))
    w("  confidence: %s" % (row.get("confidence") or 0))
    w("  band: %s" % _q(row.get("band")))
    w("  other_publishers: %s" % (row.get("other_publishers") or 0))
    w("  corroborated_by: %s" % _seq(others))
    w("  text_basis: %s" % _q(row.get("text_basis")))
    w("")
    w("# ---------------------------------------------------------------------------")
    w("# Read off the feed text verbatim. Nothing here is inferred, and nothing here is")
    w("# verified: attack_ids_mentioned are strings that appeared in the prose, NOT ids")
    w("# checked against the STIX bundle. Re-derive every one with")
    w("# `python3 tools/attack_extract.py <id>` before it goes anywhere near mitre:.")
    w("# ---------------------------------------------------------------------------")
    w("signals:")
    w("  cves: %s" % _seq(cves))
    w("  actors: %s" % _seq(actors))
    w("  tags: %s" % _seq(tags))
    w("  behaviours: %s" % _seq(behaviours))
    w("  attack_ids_mentioned: %s" % _seq(mentioned))
    w("  ioc_count: %s" % (row.get("ioc_count") or 0))
    w("")
    w("# ---------------------------------------------------------------------------")
    w("# Everything below is TODO. It is the shape of a real template so that filling it")
    w("# in is the whole of the work, but none of it can be answered from a feed entry.")
    w("# ---------------------------------------------------------------------------")
    w("info:")
    w("  name: TODO")
    w("  description: >-")
    w(_wrap("TODO. What the behaviour is and why this observation is the durable one. "
            "The lead's own headline is a starting point, not a description: " +
            (row.get("title") or ""), 4))
    w("  severity: TODO            # critical | high | medium | low")
    w("  author: huntgraph")
    w("  tags: %s" % _seq(["eti"] + tags[:4]))
    w("  references:")
    w("    - %s" % row.get("url", ""))
    w("")
    w("mitre:                      # TODO -- every id from tools/attack_extract.py")
    w("  tactics: []")
    w("  techniques: []")
    w("  sub_techniques: []")
    w("  detection_strategies: []")
    w("  analytics: []")
    w("  platforms: []")
    w("  data_sources: []")
    w("  data_components: []")
    w("")
    w("hypothesis:                 # TODO -- one hypothesis, no \"or\" in the statement")
    w("  statement: TODO")
    w("  attacker_behavior: []")
    w("  legitimate_behavior: []")
    w("  risk_indicator: []")
    w("")
    w("requires:                   # TODO")
    w("  platforms: []")
    w("  connectors: []")
    w("  logs: []")
    w("")
    w("query: []                   # TODO -- hand-written CQL, raw events, no groupBy")
    w("")
    w("evidence: {}                # TODO -- required / supporting / contradicting")
    w("")
    w("# ---------------------------------------------------------------------------")
    w("authoring:")
    w("  checklist:")
    w("    - Read the article. The feed gave a %s; it is not enough to author from."
      % (row.get("text_basis") or "title"))
    w("    - Find the behaviour, not the tool or the CVE: what does the host actually do?")
    w("    - If the evidence needs Module Load, Process Access or OS API Execution, stop")
    w("      -- that telemetry is not collected here. Record it and drop the draft.")
    w("    - Check hunt/ first. A new report on an old behaviour is an update to an")
    w("      existing template, not a new one.")
    w("    - Resolve every MITRE id with tools/attack_extract.py. Never from memory.")
    w("    - When it is finished, move it to hunt/<category>/<Txxxx-slug>/<behaviour>.yaml,")
    w("      drop the lead/signals/authoring keys and the status line, and make")
    w("      `python3 tools/validate.py --strict` pass. Until then it stays here.")
    return "\n".join(out) + "\n"


def write_drafts(rows: list[dict], drafts_dir: Path, *, now: datetime,
                 bands: tuple[str, ...] = ("high",), drafted: dict[str, dict] | None = None,
                 limit: int = 0) -> list[dict]:
    """Draft each qualifying lead that has not been drafted before.

    Returns one record per draft written: id, path, url, title and the run stamp. The
    caller persists them so tomorrow's run knows the lead is covered.
    """
    drafted = drafted or {}
    day = now.date().isoformat()
    day_dir = drafts_dir / day
    stamp = now.strftime("%Y-%m-%dT%H%M%SZ")

    # Continue the day's numbering rather than restarting it, so a second run on the
    # same day appends instead of overwriting the first run's drafts.
    existing = sorted(day_dir.glob("%s-*.yaml" % DRAFT_HEADER)) if day_dir.exists() else []
    seq = len(existing)

    written: list[dict] = []
    # (source_id, who corroborates it) for each lead drafted in this run, so the rest of
    # the coverage of the same story can be recognised and skipped. Rows arrive sorted by
    # confidence, so the one kept is the best-scoring telling.
    stories: list[tuple[str, set[str]]] = []

    for row in rows:
        if bands and row.get("band") not in bands:
            continue
        url = row.get("url", "")
        if not url or url in drafted:
            continue
        source_id = row.get("source_id", "")
        corroborators = set(_split(row.get("corroborated_by", "")))
        if any(source_id in theirs and other in corroborators
               for other, theirs in stories):
            continue
        if limit and len(written) >= limit:
            break
        stories.append((source_id, corroborators))
        seq += 1
        name = draft_name(day, seq, slugify(row.get("title", "")))
        path = day_dir / ("%s.yaml" % name)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(row, name, stamp=stamp), encoding="utf-8")
        written.append({"url": url, "draft_id": name.lower(), "title": row.get("title", ""),
                        "drafted": day, "path": str(path)})
    return written
