#!/usr/bin/env python3
"""Write stats.md: what the corpus contains, counted from the files on disk.

    python3 tools/stats.py

Generated — rerun it, never hand-edit stats.md. Tactic and technique names come from
the ATT&CK STIX bundle, like every other MITRE fact in this repo.
"""
from __future__ import annotations

import collections
import csv
import glob
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import validate as V  # noqa: E402

OUT = os.path.join(ROOT, "stats.md")
GROUPBY = re.compile(r"\bgroupBy\(")
THRESHOLD = re.compile(r"(>=|<=|>|<)\s*\(?\d|=\s*\d")


def pct(n: int, d: int) -> str:
    return "%d%%" % round(100 * n / d) if d else "—"


def table(head: list[str], rows: list[list], right: set[int] = frozenset()) -> list[str]:
    out = ["| " + " | ".join(head) + " |",
           "|" + "|".join("---:" if i in right else "---" for i in range(len(head))) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return out + [""]


def shape(q: str) -> str:
    """raw, or what an aggregating case does after its groupBy"""
    if not GROUPBY.search(q):
        return "raw"
    if "case {" in q or "case{" in q:
        return "join"
    lines = [l for l in q.split("\n") if l.strip()]
    start = max(i for i, l in enumerate(lines) if re.match(r"\s*\|?\s*groupBy\(", l))
    bal, j = 0, start
    while j < len(lines):
        bal += lines[j].count("(") - lines[j].count(")")
        if bal <= 0:
            break
        j += 1
    tail = lines[j + 1:]
    if not tail:
        return "grouped, no condition"
    return "threshold" if any(THRESHOLD.search(t) for t in tail) else "grouped, other filter"


def tracker_routing(path: str) -> dict:
    if not os.path.exists(path):
        return {}
    return {m.group(1): int(m.group(2))
            for m in re.finditer(r"^\| `([a-z-]+)` \| (\d+) \|", open(path).read(), re.M)}


def main() -> int:
    atk = V.Attack(V.load_bundle())
    tactic_name = {}
    for t in atk.tactics.values():
        for ref in t.get("external_references", []):
            if ref.get("source_name") == "mitre-attack":
                tactic_name[ref["external_id"]] = t["name"]
    byid = atk.by_attack_id

    def tname(tid: str) -> str:
        o = byid.get(tid)
        return o["name"] if o else tid

    T = []
    for p in sorted(glob.glob(os.path.join(ROOT, "hunt", "*", "T*", "**", "*.yaml"), recursive=True)):
        rel = os.path.relpath(p, ROOT)
        d = yaml.safe_load(open(p))
        parts = rel.split(os.sep)
        cql = [c for b in d["query"] if b["platform"] != "wazuh" for c in b["cases"]]
        wz = [b for b in d["query"] if b["platform"] == "wazuh"]
        ev = d["evidence"]
        T.append({
            "rel": rel, "category": parts[1], "family": parts[2].split("-")[0],
            "tactics": d["mitre"]["tactics"], "platforms": d["requires"]["platforms"],
            "severity": d["info"]["severity"],
            "shapes": [shape(c["query"]) for c in cql],
            "wazuh": bool(wz),
            "wazuh_rules": sum(len(re.findall(r"<rule\s+id=", c.get("rule", ""))) for b in wz for c in b["cases"]),
            "not_portable": sum(len(b.get("not_portable") or []) for b in wz),
            "ev": {k: len(ev[k]) for k in ("required", "supporting", "contradicting")},
            "techniques": set(d["mitre"]["techniques"]) | set(d["mitre"]["sub_techniques"]),
        })

    n = len(T)
    cases = [s for t in T for s in t["shapes"]]
    raw = sum(1 for s in cases if s == "raw")
    families = {t["family"] for t in T}
    covered_ids = set().union(*(t["techniques"] for t in T))
    wz_files = sum(1 for t in T if t["wazuh"])
    ev_tot = collections.Counter()
    for t in T:
        ev_tot.update(t["ev"])

    out = ["# Corpus statistics\n",
           "Counted from the files on disk. Generated by `python3 tools/stats.py` — "
           "regenerate, never hand-edit.\n",
           "## At a glance\n"]
    out += table(["", "Count"], [
        ["Templates (hypotheses)", n],
        ["Categories in use", len({t["category"] for t in T})],
        ["Technique families", len(families)],
        ["Distinct techniques + sub-techniques mapped", len(covered_ids)],
        ["CQL cases", len(cases)],
        ["… returning raw events", "%d (%s)" % (raw, pct(raw, len(cases)))],
        ["… aggregating", "%d (%s)" % (len(cases) - raw, pct(len(cases) - raw, len(cases)))],
        ["Templates with a Wazuh block", "%d (%s)" % (wz_files, pct(wz_files, n))],
        ["Wazuh rules", sum(t["wazuh_rules"] for t in T)],
        ["Evidence items", sum(ev_tot.values())],
    ], {1})

    out.append("## By category\n")
    rows = []
    by_cat = collections.defaultdict(list)
    for t in T:
        by_cat[t["category"]].append(t)
    for cat in sorted(by_cat, key=lambda c: -len(by_cat[c])):
        ts = by_cat[cat]
        cs = [s for t in ts for s in t["shapes"]]
        rows.append([cat, len(ts), pct(len(ts), n), len({t["family"] for t in ts}), len(cs),
                     pct(sum(1 for s in cs if s == "raw"), len(cs)),
                     sum(1 for t in ts if t["wazuh"])])
    out += table(["Category", "Templates", "Share", "Families", "CQL cases", "Raw", "Wazuh"],
                 rows, {1, 2, 3, 4, 5, 6})

    out.append("## By tactic\n")
    out.append("A template can serve more than one tactic, so these overlap.\n")
    tac = collections.Counter(x for t in T for x in t["tactics"])
    out += table(["Tactic", "Id", "Templates"],
                 [[tactic_name.get(k, k), k, v] for k, v in tac.most_common()], {2})

    out.append("## By platform and severity\n")
    plat = collections.Counter(x for t in T for x in t["platforms"])
    sev = collections.Counter(t["severity"] for t in T)
    out += table(["Platform", "Templates"], [[k, v] for k, v in plat.most_common()], {1})
    out += table(["Severity", "Templates"],
                 [[k, sev[k]] for k in ("critical", "high", "medium", "low") if sev[k]], {1})

    out.append("## Query shape\n")
    out.append("Each case is counted once. A join is counted as a join even when it also "
               "ends in a threshold, so these buckets do not overlap.\n")
    sh = collections.Counter(cases)
    out += table(["Shape", "Cases", "Share"], [
        ["raw events", sh["raw"], pct(sh["raw"], len(cases))],
        ["join (two event streams on one row)", sh["join"], pct(sh["join"], len(cases))],
        ["threshold after the groupBy", sh["threshold"], pct(sh["threshold"], len(cases))],
        ["grouped, other filter", sh["grouped, other filter"], pct(sh["grouped, other filter"], len(cases))],
        ["grouped, no condition", sh["grouped, no condition"], pct(sh["grouped, no condition"], len(cases))],
    ], {1, 2})

    out.append("## Evidence\n")
    out += table(["Bucket", "Items", "Per template"],
                 [[k, ev_tot[k], "%.1f" % (ev_tot[k] / n)] for k in ("required", "supporting", "contradicting")],
                 {1, 2})

    cov = os.path.join(ROOT, "coverage.csv")
    if os.path.exists(cov):
        status = {}
        for r in csv.DictReader(open(cov)):
            tid = (r.get("subtechnique_id") or "").strip() or (r.get("technique_id") or "").strip()
            if tid:
                status.setdefault(tid, r.get("status"))
        c = collections.Counter(status.values())
        out.append("## ATT&CK coverage\n")
        out.append("One row per technique or sub-technique in the pinned ATT&CK release. "
                   "Per-tactic detail is in [task.md](task.md).\n")
        out += table(["Status", "Targets"], [[k, v] for k, v in c.most_common()], {1})

    out.append("## Upstream rules\n")
    sig = collections.Counter(p.split(os.sep)[1] for p in
                              (os.path.relpath(x, ROOT) for x in glob.glob(os.path.join(ROOT, "hunt", "*", "sigma", "**", "*.yml"), recursive=True)))
    rows = [["Sigma threat-hunting (stored)", sum(sig.values()), ", ".join("%s %d" % kv for kv in sig.most_common()) or "—"]]
    for name, f in (("Splunk (tracked)", "splunk_tracker.md"), ("Elastic (tracked)", "elk_tracker.md")):
        r = tracker_routing(os.path.join(ROOT, "tracker", f))
        if r:
            rows.append([name, sum(r.values()), "convert %d, covered %d, blocked %d, out of scope %d"
                         % (r.get("convert", 0), r.get("covered", 0), r.get("blocked-telemetry", 0),
                            r.get("out-of-scope", 0))])
    out += table(["Source", "Rules", "Breakdown"], rows, {1})

    out.append("## Index\n")
    out.append("Every technique family, by category. Templates live at "
               "`hunt/<category>/<family>/[<sub-technique>/]<behaviour>.yaml`.\n")
    for cat in sorted(by_cat, key=lambda c: -len(by_cat[c])):
        fam = collections.defaultdict(list)
        for t in by_cat[cat]:
            fam[t["family"]].append(t)
        out.append("### %s — %d templates\n" % (cat, len(by_cat[cat])))
        rows = []
        for f in sorted(fam):
            ts = fam[f]
            folder = os.path.join("hunt", cat, next(p for p in os.listdir(os.path.join(ROOT, "hunt", cat)) if p.startswith(f + "-")))
            subs = sorted({x for t in ts for x in t["techniques"] if x.startswith(f + ".")})
            rows.append(["[%s](%s)" % (f, folder), tname(f), len(ts), ", ".join(subs) or "—"])
        out += table(["Technique", "Name", "Templates", "Sub-techniques"], rows, {2})

    open(OUT, "w").write("\n".join(out).rstrip() + "\n")
    print("wrote stats.md: %d templates, %d cases, %d families" % (n, len(cases), len(families)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
